### ISSUE TITLE
[Bug]: DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.

### ISSUE THREAD

**Issue by spitzlei** [Status-Page/Status-Page#650]
### Description of the Bug

 INFO    -  DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
 Material emoji logic has been officially moved into mkdocs-material
 version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
 instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

 ```
 markdown_extensions:
   - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
 ```

 'mkdocs_material_extensions' is deprecated and will no longer be
 supported moving forward. This is the last release.

   File "/usr/src/app/venv/lib/python3.12/site-packages/materialx/emoji.py", line 118, in twemoji
     return _patch_index(options)
   File "/usr/src/app/venv/lib/python3.12/site-packages/materialx/emoji.py", line 68, in _deprecated_func
     warnings.warn(

 WARNING -  Material emoji logic has been officially moved into mkdocs-material
 version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
 instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

### Expected behavior

Please use Material's 'material.extensions.emoji.twemoji'
 instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

### Reproduction

Checkout the current Version of status-page and start the installation.

### Version

= 2.0.0 (Stable)

### Information about your Device

**Desktop (please complete the following information):**
 - OS: Linux
